# Zero dimension array
* 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [2]:
import numpy as np 
arr = np.array(100)
print(arr)

100


# 1-D Arrays

In [4]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


# 2-D Arrays

In [7]:
import numpy as np 
arr = np.array([[1,2,3,4,5,6],[6,5,4,3,2,1]])
print(arr)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]


# 3-D arrays

In [11]:
import numpy as np 
arr = np.array([[[1,2,3,4],[5,6,7,8]]  , [[8,7,6,5],[4,3,2,1]]])
print(arr)
print(arr.ndim)  # ndim is a attribute for checking the how many dimention in your array 

[[[1 2 3 4]
  [5 6 7 8]]

 [[8 7 6 5]
  [4 3 2 1]]]
3


# creating no of dimention (ndmin)
* When the array is created, you can define the number of dimensions by using the ndmin argument.

In [1]:
import numpy as np 
array = np.array((1,2,5,48,7,6), ndmin= 4)
print(array)
print(array.ndim)

[[[[ 1  2  5 48  7  6]]]]
4


# array indexing 

In [9]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


# operation 

In [11]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])
print(arr[0] + arr[3] - arr[0])   # 1 + 4 - 1 = 4

4


* operation in the 2D array 

In [17]:
import numpy as np 
arr = np.array([[1,2,3,4,5,6],[3,2,5,4,6]])
print(arr[0,2])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.