# Zero dimension array
* 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [2]:
import numpy as np 
arr = np.array(100)
print(arr)

100


# 1-D Arrays

In [4]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


# 2-D Arrays

In [7]:
import numpy as np 
arr = np.array([[1,2,3,4,5,6],[6,5,4,3,2,1]])
print(arr)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]


# 3-D arrays

In [11]:
import numpy as np 
arr = np.array([[[1,2,3,4],[5,6,7,8]]  , [[8,7,6,5],[4,3,2,1]]])
print(arr)
print(arr.ndim)  # ndim is a attribute for checking the how many dimention in your array 

[[[1 2 3 4]
  [5 6 7 8]]

 [[8 7 6 5]
  [4 3 2 1]]]
3
