1.	Create a 2D array with 1 on border  and 0 on inside.
 
2.	Find indices of Non-zero elements from A[2,3,0,1,0,9].
3.	Create a zero  one D vector of size 10 but 5th value should be 9.
4.	Create a 3×3 NumPy array of all True.
5.	Create a 4×4 array and extract its first row and last column.
6.	Get the positions where elements of array a and b match.
7.	Sorting a NumPy array based on a specific column.
Ex:   Array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]
Note:(Sort records according 2nd column)
8.	8.Replace all odd numbers in a NumPy array with -1.

In [16]:
# Create a 2D array with 1 on border and 0 on inside.
import numpy as np 
arr = np.ones(100).reshape(10,10)
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
