1.	Create a 2D array with 1 on border  and 0 on inside.
 
2.	Find indices of Non-zero elements from A[2,3,0,1,0,9].
3.	Create a zero  one D vector of size 10 but 5th value should be 9.
4.	Create a 3×3 NumPy array of all True.
5.	Create a 4×4 array and extract its first row and last column.
6.	Get the positions where elements of array a and b match.
7.	Sorting a NumPy array based on a specific column.
Ex:   Array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]
Note:(Sort records according 2nd column)
8.	8.Replace all odd numbers in a NumPy array with -1.

# 1.# Create a 2D array with 1 on border and 0 on inside.

In [28]:
import numpy as np 
arr = np.ones(100).reshape(10,10)
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 2 .Find indices of Non-zero elements from A[2,3,0,1,0,9].

In [29]:
A = np.array([2,3,0,1,0,9])
index = np.nonzero(A) # fast and simple 
ind = np.where(A != 0) # fast but best use for conditional stuation 
inde = np.arange(len(A))[A != 0] # slightly longer but if you went output in array then this is upmm  
print(inde)
print(index)
print(ind)

[0 1 3 5]
(array([0, 1, 3, 5], dtype=int64),)
(array([0, 1, 3, 5], dtype=int64),)


# 3. Create a zero one D vector of size 10 but 5th value should be 9.

In [27]:
array = np.zeros(10)
array[4] = 9
print(array)

[0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]


# 4. Create a 3×3 NumPy array of all True.

In [42]:
True_arr = np.ones((3,3) , dtype=bool)
False_arr = np.zeros((5,5) , dtype=bool)
print(bool_arr)
print(False_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


# 5. Create a 4×4 array and extract its first row and last column.

In [414]:
# array_4_4 = np.arange(16).reshape(4,4)
array_4_4 = np.random.randint(0,16,size = (4,4))
print(array_4_4)
first_row  =  array_4_4[0]
last_col = array_4_4[:,-1]
print(first_row)
print(last_col)
result = array_4_4[0],array_4_4[:,-1] # fc (farde code )
print(result)

[[ 6  8  5  8]
 [15  7 15  6]
 [ 6 12  7 13]
 [ 6  4  1  3]]
[6 8 5 8]
[ 8  6 13  3]
(array([6, 8, 5, 8]), array([ 8,  6, 13,  3]))


# 6. Get the positions where elements of array a and b match.

In [400]:
arr1 = np.random.randint(0,10,7)
arr2 = np.random.randint(0,10,7)
indexs = np.where(arr1 == arr2)
print(f'arr1:- {arr1}\narr2:- {arr2}')
print('arr1 = arr2 this is the potions on same arr values:- ',indexs)

arr1:- [9 1 0 7 4 5 1]
arr2:- [8 8 7 5 5 0 4]
arr1 = arr2 this is the potions on same arr values:-  (array([], dtype=int64),)


# 7 Sorting a NumPy array based on a specific column. Ex: Array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]] Note:(Sort records according 2nd column)

In [422]:
ar = np.array([[34,43,73] , 
               [82,22,12] , 
               [53,94,66]])
sort = ar[ar[:,1].sort() ]
print(sort)

[[[34 22 73]
  [82 43 12]
  [53 94 66]]]


# 8.Replace all odd numbers in a NumPy array with -1.

In [451]:
shinchan = np.random.randint(1,30, size = (4,4))
print("rondom\n",shinchan)
shinchan[shinchan % 2 != 0] = -1
print('shinchan :-\n',shinchan)

rondom
 [[29 11 21 11]
 [10 17 20  2]
 [28 24 14  5]
 [16 12 21 17]]
shinchan :-
 [[-1 -1 -1 -1]
 [10 -1 20  2]
 [28 24 14 -1]
 [16 12 -1 -1]]
