In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
np.save('my_array.npy', arr)   # Save array
load = np.load("my_array.npy")
print(load)

[1 2 3 4 5]


In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

np.savetxt('data.csv', arr, delimiter=',', fmt='%d')

loaded = np.loadtxt('data.csv', delimiter=',')
print(loaded)


[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
arr = np.array([[1.23, 4.56], [7.89, 0.12]])
np.savetxt('data.csv', arr, delimiter=',', fmt='%.2f',header='this is useless data', footer= 'bhag meme', comments= '@')

| Format Code | Meaning                        | Example                 |
| ----------- | ------------------------------ | ----------------------- |
| `%d`        | Integer (no decimals)          | `5`, `12`               |
| `%f`        | Floating-point (decimal)       | `5.000000`, `12.500000` |
| `%.2f`      | Floating-point with 2 decimals | `5.00`, `12.50`         |
| `%s`        | String                         | `'hello'`               |
